alias grep='grep --color'
alias ls='ls -G'
alias ll='ls -alFh'
alias la='ls -Ah'
alias l='ls -CFh'
alias cl='find . -name "*~" -exec rm -vf {} \; && find . -name "#*#" -exec rm -vf {} \;'
alias clm='find . -name "._*" -exec rm -vf {} \; && find . -name ".DS_Store" -exec rm -vf {} \;'
